-- H2 2.2.224;
;
CREATE USER IF NOT EXISTS "LEO" SALT '875a8ab78d791f9b' HASH 'fdada66327e04dcd2694fc72da30ad1481681435d8a156053fa852d0df622233' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."ASSOCIATEDS"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."ASSOCIATEDS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATEDS;
CREATE MEMORY TABLE "PUBLIC"."MAINS"(
    "ASSOCIATED_ID" UUID,
    "ID" UUID NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."MAINS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MAINS;
ALTER TABLE "PUBLIC"."MAINS" ADD CONSTRAINT "PUBLIC"."FKSL1SUEX5OUOU1QC0SMDY9HLPN" FOREIGN KEY("ASSOCIATED_ID") REFERENCES "PUBLIC"."ASSOCIATEDS"("ID") NOCHECK;